#!/usr/bin/env bash

set -e

usage() {
  if [ -z "$1" ]; then
    code=0
  else
    echo "error: $1" >&2
    code=1
  fi

  echo "Usage: $(basename $0) [opts]" >&2
  echo >&2
  echo "Options:" >&2
  echo >&2
  echo "  -e/E, --[no-]exports    include exports for closure-compiler (default=false)" >&2
  echo "  -h,   --help            print this help message" >&2
  exit $code
}

exports=false

while [ $# -gt 0 ]; do
  arg=$1
  shift

  case "$arg" in
    -h|--help)
      usage
      ;;

    -e|--exports)
      exports=true
      ;;

    -E|--no-exports)
      exports=false
      ;;

    -*)
      usage "unexpected option: $arg"
      ;;

    *)
      usage "unexpected argument: $arg"
      ;;
  esac
done

rename-export() {
  perl -pe "s/module.exports = /$1 = /"
}

process-file() {
  file=$1
  global=$2
  base=$(basename $file .js | perl -pe "s/\\./_/g")

  if [ -z "$global" ]; then
    global="${base}__module"
    echo "var $global;"
  fi

  echo "/*"
  echo " * $file CONTENTS"
  echo " */"

  cat $file | rename-export $global

  if [ "$exports" == "true" ]; then
    echo "/*"
    echo " * $file EXPORTS"
    echo " */"

    ./script/build-exports $file
  fi
}

process-file lib/index.js "this[\"stround\"]"
