#!/usr/bin/env bash

set -e

usage() {
  if [ -z "$1" ]; then
    code=0
  else
    echo "error: $1" >&2
    code=1
  fi

  echo "Usage: $(basename $0) [--help] [--[no-]wrap]" >&2
  exit $code
}

wrap=true

while [ $# -gt 0 ]; do
  arg=$1
  shift

  case "$arg" in
    -h|--help)
      usage
      ;;

    -w|--wrap)
      wrap=true
      ;;

    -W|--no-wrap)
      wrap=false
      ;;

    -*)
      usage "unexpected option: $arg"
      ;;

    *)
      usage "unexpected argument: $arg"
      ;;
  esac
done

js=$(mktemp /tmp/source.js.XXXXX)
$(dirname $0)/build --no-wrap --exports > $js

if [ "$wrap" == "true" ]; then
  echo '(function(window) {'
fi

set -x

closure-compiler \
  --compilation_level ADVANCED_OPTIMIZATIONS \
  --js $js \
  --jscomp_error checkTypes

set +x

if [ "$wrap" == "true" ]; then
  echo '}).call(this, this)'
fi
