#!/usr/bin/env bash

set -e

usage() {
  if [ -z "$1" ]; then
    code=0
  else
    echo "error: $1" >&2
    code=1
  fi

  echo "Usage: $(basename $0) [--help]" >&2
  exit $code
}

while [ $# -gt 0 ]; do
  arg=$1
  shift

  case "$arg" in
    -h|--help)
      usage
      ;;

    -*)
      usage "unexpected option: $arg"
      ;;

    *)
      usage "unexpected argument: $arg"
      ;;
  esac
done

js=$(mktemp /tmp/source.js.XXXXX)
$(dirname $0)/build --exports > $js

set -x

closure-compiler \
  --compilation_level ADVANCED_OPTIMIZATIONS \
  --js $js \
  --jscomp_error checkTypes \
  --jscomp_error undefinedVars \
  --jscomp_error uselessCode \
  --jscomp_error checkRegExp \
  --jscomp_off globalThis
